{% set version = "4.0.1" %}

package:
  name: oct2py
  version: {{ version }}

source:
  fn: oct2py-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/oct2py/oct2py-{{ version }}.tar.gz
  sha256: 69a68db10d21c37f28877f6bc01883e13e723ac192e844504be40dd5864c7436

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - ipython
    - octave_kernel >=0.25.0

about:
  home: http://github.com/blink1073/oct2py
  license: MIT
  license_file: LICENSE.txt
  summary: 'Python to GNU Octave bridge --> run m-files from python.'

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
