{% set version = "4.1.0" %}

package:
  name: oct2py
  version: {{ version }}

source:
  fn: oct2py-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/oct2py/oct2py-{{ version }}.tar.gz
  sha256: a6637f3c264d4d5755fd905d83cee447b859a871833edc3065f8bbb4e075587e

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - ipython
    - octave_kernel >=0.25.0

about:
  home: http://github.com/blink1073/oct2py
  license: MIT
  license_file: LICENSE.txt
  summary: 'Python to GNU Octave bridge --> run m-files from python.'

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
