{% set version = "3.6.5" %}

package:
    name: oct2py
    version: {{ version }}

source:
    fn: oct2py-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/o/oct2py/oct2py-{{ version }}.tar.gz
    sha256: 490011651d66a77323ebdb9c6dced993eeefc92913b5c87b1e0283001d33afe7

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - ipython

about:
    home: http://github.com/blink1073/oct2py
    license: MIT
    summary: Python to GNU Octave bridge --> run m-files from python

extra:
    recipe-maintainers:
        - blink1073
        - ocefpaf
