{% set version = "3.5.9" %}

package:
    name: oct2py
    version: {{ version }}

source:
    fn: oct2py-{{ version }}.tar.gz
    url: https://github.com/blink1073/oct2py/archive/v{{ version }}.tar.gz
    sha256: f58a92afce6d350a5728e711cf8e6422b5e97426ecffea185a33c1983c0ebfb2

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - ipython

about:
    home: http://github.com/blink1073/oct2py
    license: MIT
    summary: Python to GNU Octave bridge --> run m-files from python

extra:
    recipe-maintainers:
        - blink1073
        - ocefpaf
