{% set version = "5.0.0" %}

package:
  name: oct2py
  version: {{ version }}

source:
  fn: oct2py-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/oct2py/oct2py-{{ version }}.tar.gz
  sha256: 0b808d870b4ebbe9c5063e6a540fa9535796470c9711e4a7736186096929a87b

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - ipython
    - octave_kernel >=0.30.0

about:
  home: http://github.com/blink1073/oct2py
  license: MIT
  license_file: LICENSE.txt
  summary: 'Python to GNU Octave bridge --> run m-files from python.'

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
