{% set version = "3.7.0" %}

package:
    name: oct2py
    version: {{ version }}

source:
    fn: oct2py-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/o/oct2py/oct2py-{{ version }}.tar.gz
    sha256: 9858f84ecb7825007330371d5d083dd5e1df4ddf298ca94ab29722328d82f39f

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - ipython

about:
    home: http://github.com/blink1073/oct2py
    license: MIT
    summary: Python to GNU Octave bridge --> run m-files from python

extra:
    recipe-maintainers:
        - blink1073
        - ocefpaf
