travis:
  secure:
    BINSTAR_TOKEN: YIdFPBcbdIqvmxlTBMJ1rEOEonR4kDbjjhPfgzUMnppdtKQe8cfaXTMk//18fqJSstu+Nnh1+RlehG7uE3hgybZwe1vScemLUFCQ+JXQz8TyqO6A908Dw0SGRLGTqTE4K8Stdc8mJUB8+67pP6QeIq+bb7I4QSPcTdqWt1mBkaxOdSdnlwK+FLmy8HuPGmipmtdyCWvCzt+qUsQI2cZUrMFHHwOcYluSCkWrFtye6EPdkte2+TLLqbxLmXpQq1uDWsPSq7qUhU/RerWzFea9vTlIv03qbWP5k1VipUwnwe4zVJ7+oFgWWKIPF0wjje8+lKiAAJ2kL3CxvTaROWzeEUQ2simSipmY3odBuU1Lm27VMFGz1bWg2PeogNDW9xbogur1aEqFQwcYp3ExI4QnUNHGmCZO4liMInh3eG97Z8PHj645XMFpzu/rmJyxxTDan3plJ4oxHMEvhqwqRMGUuM7KrpetinbpxLyakkhpLWlvLzAZ5VpIX5SWpEe2eO972ydzgBXZ1iH3go+dxyloKKtuqnO+iUazwk3HRS/QsJ1ml9lk/HjP2qy3dD4cnNIkT9OOeYI6ni16BBRmU5G49ejnQc0cMGBPsLFBnjj7x2zgrxNCJc8i3NVwnrNfOsjb8QEiOHrPVPptTsN4Rf8C47QxsJ9sj/jJ28K4kiaNX4c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
