travis:
  secure:
    BINSTAR_TOKEN: c+LzgvmQayckkvc0MpPg97y7cfirmqSQnEi0uUBJKBWmegszCJgo9qIVAF18lQz0PXOT2nvaQcvandK++nPiUcy5WQK9jQaY+H+arFTMwQvU5pkhEyx6xYtnlTXmO1NGCODfjdyizrMK0qMN0gDzO+0PLw+pNq7QI9pRt3BmEvmSG2cfNC7xKH8Niu+qwXR1F+DdkQJxLIcwpsoEVuIBFl2YVDIDcxfCNdbAgN6pgCsBMRsTOtjM2rP+RuvHGi7R1OXW5F9Qj2i/NQ4s7LOfqgU9P05T5SKP6O1buA+mqFiDYZlnHhcRmyDxFydH/yZXJpBWsuaMAkD/GuCc1W2y6YI1cuNUe/bjjQleLNq1iZ/6CDs7p0CIlYrboCTbwAR5d2+utajRdZcmcG5p0kN0xRUMBmSM5tQ3K6fa1oTZZMd1rDhGkTPNYW5AHNtiWyfQ5YLLeCLUpk4wInB3cQpU3I2JfUIJCZ3hFdn1HuUeiJfG0AE0Ft3VsQJeELkM/kfQy+cO8p5wwBPqNkxOy7x5XTm/+/GN4OFSy4X+dquWrBiBewSDAUSj+cOwzeJ8lmZBojEzQLzaDqdxEYpOy31ZV0wEyCfRYLNYfWShw+iGYlMufYzPTSroUvOO/po9fadiMFEDV/KSbCDeFsSBbnvmxMeL34NKicX2ohZW+B9RmLM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
